// Auto-generated wrapper for hello_world
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 0 (slots 0-0)
// Return value: slot 31


#include <stdint.h>
#include "hello.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48211200;


    // Call original function: hello_world
    hello_world();

    // No return value (void function)

    return ESP_OK;
}
