// Auto-generated wrapper for modify_array
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 2 (slots 0-1)
// Return value: slot 31


#include <stdint.h>
#include "bidirectional.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48211c60;

    // Argument 0: POINTER type int*
    int* data = (int*) io[0];

    // Argument 1: VALUE type int
    int len = *(int*)& io[1];

    // Call original function: modify_array
    int result = modify_array(data, len);

    // Write result (int) to slot 31
    *(int*)&io[31] = result;

    return ESP_OK;
}
