// Auto-generated wrapper for smart_test
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 3 (slots 0-2)
// Return value: slot 31


#include <stdint.h>
#include "smart_test.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48211c00;

    // Argument 0: POINTER type int*
    int* arr = (int*) io[0];

    // Argument 1: VALUE type int
    int len = *(int*)& io[1];

    // Argument 2: VALUE type float
    float scale = *(float*)& io[2];

    // Call original function: smart_test
    int result = smart_test(arr, len, scale);

    // Write result (int) to slot 31
    *(int*)&io[31] = result;

    return ESP_OK;
}
