// Auto-generated wrapper for InterpolateWaveHermite
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 3 (slots 0-2)
// Return value: slot 31


#include <stdint.h>
#include "test_func.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x50000000;

    // Argument 0: POINTER type float*
    float* table = (float*) io[0];

    // Argument 1: VALUE type int32_t
    int32_t index_integral = *(int32_t*)& io[1];

    // Argument 2: VALUE type float
    float index_fractional = *(float*)& io[2];

    // Call original function: InterpolateWaveHermite
    float result = InterpolateWaveHermite(table, index_integral, index_fractional);

    // Write result (float) to slot 31
    io[31] = *(int32_t*)& result;

    return ESP_OK;
}
