// Auto-generated wrapper for sum_array
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 2 (slots 0-1)
// Return value: slot 31


#include <stdint.h>
#include "sum_array.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48214e00;

    // Argument 0: POINTER type int8_t*
    int8_t* arr = (int8_t*) io[0];

    // Argument 1: VALUE type int
    int len = *(int*)& io[1];

    // Call original function: sum_array
    int result = sum_array(arr, len);

    // Write result (int) to slot 31
    io[31] = (int32_t) result;

    return ESP_OK;
}
