// Auto-generated wrapper for test_all_types
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 8 (slots 0-7)
// Return value: slot 31


#include <stdint.h>
#include "types_test.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x4ff3fb00;

    // Argument 0: VALUE type int8_t
    int8_t a = *(int8_t*)& io[0];

    // Argument 1: VALUE type uint8_t
    uint8_t b = *(uint8_t*)& io[1];

    // Argument 2: VALUE type int16_t
    int16_t c = *(int16_t*)& io[2];

    // Argument 3: VALUE type uint16_t
    uint16_t d = *(uint16_t*)& io[3];

    // Argument 4: VALUE type int32_t
    int32_t e = *(int32_t*)& io[4];

    // Argument 5: VALUE type float
    float f = *(float*)& io[5];

    // Argument 6: POINTER type int32_t*
    int32_t* array_in = (int32_t*) io[6];

    // Argument 7: VALUE type int32_t
    int32_t len = *(int32_t*)& io[7];

    // Call original function: test_all_types
    int32_t result = test_all_types(a, b, c, d, e, f, array_in, len);

    // Write result (int32_t) to slot 31
    *(int32_t*)&io[31] = result;

    return ESP_OK;
}
