// Auto-generated wrapper for mnist_inference
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 19 (slots 0-18)
// Return value: slot 31


#include <stdint.h>
#include "mnist_inference.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x00030004;

    // Argument 0: POINTER type int8_t*
    int8_t* input = (int8_t*) io[0];

    // Argument 1: POINTER type int8_t*
    int8_t* w_conv1 = (int8_t*) io[1];

    // Argument 2: POINTER type int8_t*
    int8_t* b_conv1 = (int8_t*) io[2];

    // Argument 3: POINTER type int8_t*
    int8_t* w_conv2 = (int8_t*) io[3];

    // Argument 4: POINTER type int8_t*
    int8_t* b_conv2 = (int8_t*) io[4];

    // Argument 5: POINTER type int8_t*
    int8_t* w_fc1 = (int8_t*) io[5];

    // Argument 6: POINTER type int8_t*
    int8_t* b_fc1 = (int8_t*) io[6];

    // Argument 7: POINTER type int8_t*
    int8_t* w_fc2 = (int8_t*) io[7];

    // Argument 8: POINTER type int8_t*
    int8_t* b_fc2 = (int8_t*) io[8];

    // Argument 9: VALUE type int32_t
    int32_t e_in = *(int32_t*)& io[9];

    // Argument 10: VALUE type int32_t
    int32_t e_conv1_w = *(int32_t*)& io[10];

    // Argument 11: VALUE type int32_t
    int32_t e_conv1_act = *(int32_t*)& io[11];

    // Argument 12: VALUE type int32_t
    int32_t e_conv2_w = *(int32_t*)& io[12];

    // Argument 13: VALUE type int32_t
    int32_t e_conv2_act = *(int32_t*)& io[13];

    // Argument 14: VALUE type int32_t
    int32_t e_fc1_w = *(int32_t*)& io[14];

    // Argument 15: VALUE type int32_t
    int32_t e_fc1_act = *(int32_t*)& io[15];

    // Argument 16: VALUE type int32_t
    int32_t e_fc2_w = *(int32_t*)& io[16];

    // Argument 17: POINTER type int8_t*
    int8_t* scratch = (int8_t*) io[17];

    // Argument 18: POINTER type uint32_t*
    uint32_t* timing = (uint32_t*) io[18];

    // Call original function: mnist_inference
    int32_t result = mnist_inference(input, w_conv1, b_conv1, w_conv2, b_conv2, w_fc1, b_fc1, w_fc2, b_fc2, e_in, e_conv1_w, e_conv1_act, e_conv2_w, e_conv2_act, e_fc1_w, e_fc1_act, e_fc2_w, scratch, timing);

    // Write result (int32_t) to slot 31
    *(int32_t*)&io[31] = result;

    return ESP_OK;
}
