// Auto-generated wrapper for process_audio
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 6 (slots 0-5)
// Return value: slot 31


#include <stdint.h>
#include "biquad.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x4ff3f980;

    // Argument 0: POINTER type float*
    float* readBufferFloat = (float*) io[0];

    // Argument 1: VALUE type int
    int readBufferLength = *(int*)& io[1];

    // Argument 2: POINTER type float*
    float* coeffs_lpf = (float*) io[2];

    // Argument 3: POINTER type float*
    float* w_lpf1 = (float*) io[3];

    // Argument 4: POINTER type float*
    float* w_lpf2 = (float*) io[4];

    // Argument 5: POINTER type float*
    float* w_lpf3 = (float*) io[5];

    // Call original function: process_audio
    uint32_t result = process_audio(readBufferFloat, readBufferLength, coeffs_lpf, w_lpf1, w_lpf2, w_lpf3);

    // Write result (uint32_t) to slot 31
    *(uint32_t*)&io[31] = result;

    return ESP_OK;
}
