// Auto-generated wrapper for compute_sum
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 2 (slots 0-1)
// Return value: slot 31

#include "compute.h"  // Include generated header


typedef int esp_err_t;
#define ESP_OK 0

esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48212780;

    // Argument 0: VALUE type int
    int a = *(int*)& io[0];

    // Argument 1: VALUE type int
    int b = *(int*)& io[1];

    // Call original function: compute_sum
    float result = compute_sum(a, b);

    // Write result (float) to slot 31
    io[31] = *(int32_t*)& result;

    return ESP_OK;
}
