// Auto-generated wrapper for apply_gain
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 3 (slots 0-2)
// Return value: slot 31


#include <stdint.h>
#include "audio_processing.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48211710;

    // Argument 0: POINTER type uint8_t*
    uint8_t* data = (uint8_t*) io[0];

    // Argument 1: VALUE type int
    int len = *(int*)& io[1];

    // Argument 2: VALUE type float
    float gain = *(float*)& io[2];

    // Call original function: apply_gain
    float result = apply_gain(data, len, gain);

    // Write result (float) to slot 31
    *(float*)&io[31] = result;

    return ESP_OK;
}
