// Auto-generated wrapper for sum_point
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 3 (slots 0-2)
// Return value: slot 31


#include <stdint.h>
#include "geometry.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48211430;

    // Argument 0: POINTER type Point*
    Point* p = (Point*) io[0];

    // Argument 1: VALUE type int8_t
    int8_t z = *(int8_t*)& io[1];

    // Argument 2: POINTER type uint16_t*
    uint16_t* arr = (uint16_t*) io[2];

    // Call original function: sum_point
    float result = sum_point(p, z, arr);

    // Write result (float) to slot 31
    *(float*)&io[31] = result;

    return ESP_OK;
}
