// Auto-generated wrapper for complex_c_test
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 4 (slots 0-3)
// Return value: slot 31


#include <stdint.h>
#include "main.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48212c80;

    // Argument 0: POINTER type int*
    int* data = (int*) io[0];

    // Argument 1: VALUE type int
    int len = *(int*)& io[1];

    // Argument 2: VALUE type float
    float scale = *(float*)& io[2];

    // Argument 3: VALUE type float
    float offset = *(float*)& io[3];

    // Call original function: complex_c_test
    int result = complex_c_test(data, len, scale, offset);

    // Write result (int) to slot 31
    *(int*)&io[31] = result;

    return ESP_OK;
}
