// Auto-generated wrapper for double_and_sum
// Generated by esp32-jit wrapper system
// Args array size: 32 slots (128 bytes)
// Arguments: 2 (slots 0-1)
// Return value: slot 31


#include <stdint.h>
#include "array_ops.h"  // Include generated header

// Wrapper function to handle argument unpacking and return value
// Args are passed via a memory region (args_addr)
// [0..N-1]: Arguments
// [N]: Return value (if any)
typedef int esp_err_t;
#define ESP_OK 0


esp_err_t call_remote(void) {
    volatile int32_t *io = (volatile int32_t *)0x48210b80;

    // Argument 0: POINTER type int*
    int* array = (int*) io[0];

    // Argument 1: VALUE type int
    int length = *(int*)& io[1];

    // Call original function: double_and_sum
    int result = double_and_sum(array, length);

    // Write result (int) to slot 31
    *(int*)&io[31] = result;

    return ESP_OK;
}
